version: '3'
services:
  nodejs-server:
    build:
      context: ./api
    ports:
      - "3080:3080"
    container_name: node-api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
  react-ui:
    build:
      context: ./reactapp1
    ports:
      - "3001:3001"
    container_name: reactapp1
    stdin_open: true
    volumes:
       - ./my-app:/usr/src/app/reactapp1
       - /usr/src/app/my-app/node_modules