server:
  port: ${PORT:8080}
  servlet:
    context-path: /information

logging: 
  file:
    path: .
    name: logs/${spring.application.name:phonebook-service}.log
  level: 
    '[com.evertcode]': INFO
    '[org.hibernate]': ERROR
    '[org.springframework]': INFO
    '[org.springframework.web]': ERROR
    root: ERROR
  pattern: 
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n'
    file: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n'

spring: 
  application:
    name: phonebook-service
  main: 
    banner-mode: "off"